// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgw-ww2eO4GIm-kFR4V1O3IkbFA_AZl3k',
    appId: '1:616938197388:web:b293bea6dcaad605f6c6a9',
    messagingSenderId: '616938197388',
    projectId: 'spartans-4f161',
    authDomain: 'spartans-4f161.firebaseapp.com',
    storageBucket: 'spartans-4f161.firebasestorage.app',
    measurementId: 'G-4W6R0ZJVBP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-NuVm_tItJagNSQndOLFmZcHpCvzBIkc',
    appId: '1:616938197388:android:e0154a1592aa0f12f6c6a9',
    messagingSenderId: '616938197388',
    projectId: 'spartans-4f161',
    storageBucket: 'spartans-4f161.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKmHfHR3Yq0y8qE_bx0cqqmREHOBzbykE',
    appId: '1:616938197388:ios:55735dd25c18db02f6c6a9',
    messagingSenderId: '616938197388',
    projectId: 'spartans-4f161',
    storageBucket: 'spartans-4f161.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKmHfHR3Yq0y8qE_bx0cqqmREHOBzbykE',
    appId: '1:616938197388:ios:55735dd25c18db02f6c6a9',
    messagingSenderId: '616938197388',
    projectId: 'spartans-4f161',
    storageBucket: 'spartans-4f161.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgw-ww2eO4GIm-kFR4V1O3IkbFA_AZl3k',
    appId: '1:616938197388:web:720563e1e9ebc094f6c6a9',
    messagingSenderId: '616938197388',
    projectId: 'spartans-4f161',
    authDomain: 'spartans-4f161.firebaseapp.com',
    storageBucket: 'spartans-4f161.firebasestorage.app',
    measurementId: 'G-X93Q7K2CQ5',
  );
}
